services:
  web1:
    build:
      context: .
      dockerfile: DockerfileApache_kiskoramosUGR
    image: kiskoramosugr-apache-image:p1
    volumes:
      - ./web_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.2
      red_admin:
        ipv4_address: 172.18.0.2
    ports:
      - "8081:80"
    


  web2:
    image: kiskoramosugr-apache-image:p1
    volumes:
      - ./web_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.3
      red_web:
        ipv4_address: 192.168.10.3
    ports:
      - "8082:80"
    cap_add:
      - NET_ADMIN

  web3:
    image: kiskoramosugr-apache-image:p1
    volumes:
      - ./web_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.4
      red_web:
        ipv4_address: 192.168.10.4
    ports:
      - "8083:80"

  web4:
    image: kiskoramosugr-apache-image:p1
    volumes:
      - ./web_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.5
      red_web:
        ipv4_address: 192.168.10.5
    ports:
      - "8084:80"

  web5:
    build:
      context: .
      dockerfile: DockerfileNginx_kiskoramosUGR
    image: kiskoramosugr-nginx-image:p1
    volumes:
      - ./nginx_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.6
      red_web:
        ipv4_address: 192.168.10.6
    ports:
      - "8085:80"

  web6:
    image: kiskoramosugr-nginx-image:p1
    volumes:
      - ./nginx_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.7
      red_web:
        ipv4_address: 192.168.10.7
    ports:
      - "8086:80"

  web7:
    image: kiskoramosugr-nginx-image:p1
    volumes:
      - ./nginx_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.8
      red_web:
        ipv4_address: 192.168.10.8
    ports:
      - "8087:80"

  web8:
    image: kiskoramosugr-nginx-image:p1
    volumes:
      - ./nginx_kiskoramosUGR:/var/www/html
    networks:
      red_servicios:
        ipv4_address: 192.168.20.9
      red_web:
        ipv4_address: 192.168.10.9
    ports:
      - "8088:80"

networks:
  red_web:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_servicios:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
  red_admin:
      driver: bridge
      ipam:
        config:
          - subnet: 172.18.0.0/24
